[package]
name = "idm-server"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "^0.4"
env_logger = "^0.11"
#
#
sal-core = { git = "https://github.com/a-givertzman/rust-sal-core.git", tag = "0.0.3" }
debugging = { git = "https://github.com/a-givertzman/rust-debuging.git", tag = "0.0.1" }
